spring:
  application:
    name: 'tistory'

  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_264
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nhn_academy_264
    password: yV6aeany!
    dbcp2:
      validation-query: select 1

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true



